name: Merge Rules and Publish

on:
  schedule:
    - cron: '0 20 * * *'  # 每天 UTC 时间 20:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  merge-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 PAT 检出代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests
          pip install loguru
          pip install dnspython
          pip install httpx
          pip install IPy tld
          pip install pytz
          pip install geoip2

      - name: Download GeoLite2 database
        run: curl -L https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb -o Country.mmdb

      - name: Run merge_rules.py
        run: python merge_rules.py

      - name: Run dispose.py
        run: python dispose.py

      - name: Check if files exist
        run: ls -l

      - name: Clean up __pycache__
        run: rm -rf __pycache__

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git rm -f __pycache__/config.cpython-312.pyc || true
          git add all.txt beforeall.txt all-lite.txt all-cn.txt Country.mmdb dispose.log  # 添加所有生成文件和数据库
          git commit -m "Update all.txt, beforeall.txt, and all-lite.txt - $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git main
